version: '3.8'

services:
  pintos:
    image: davidchen871/pintos
    container_name: pintos_lab3
    stdin_open: true  
    tty: true         
    restart: no       
    volumes:
    -  /home/os/lab3/pintos-lab3/pintos:/home/pintos
    environment:
      - PINTOS_DIR=/home/pintos